services:
  # A Docker web service
  - type: web
    name: loan-approval-predictor
    runtime: python>=3.7.0
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
